# Generated by Django 5.0.3 on 2024-03-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_paymentinfo_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax",
            field=models.FloatField(default=0.0),
        ),
    ]
