# Generated by Django 5.0.3 on 2024-03-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_otp_is_active_alter_order_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinfo",
            name="payment_id",
            field=models.CharField(max_length=255),
        ),
    ]
