# Generated by Django 5.0.3 on 2024-04-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_paymentinfo_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="reason",
            field=models.CharField(
                choices=[
                    ("EMPLOYEE_DEPOSIT", "Employee Deposit"),
                    ("REFUND", "Refund"),
                    ("EMPLOYEE_WITHDRAW", "Employee Withdraw"),
                    ("GIFT_DEPOSIT", "Gift Deposit"),
                    ("PROMOTIONAL_DEPOSIT", "Promotional Deposit"),
                    ("HOST_DEPOSIT", "Host Deposit"),
                    ("COMPLAIN_DEPOSIT", "Complain Deposit"),
                    ("CUSTOMER_DEPOSIT", "Customer Deposit"),
                    ("CHARGE_DEDUCTION", "Charge Deduction"),
                ],
                default="CUSTOMER_DEPOSIT",
                max_length=255,
            ),
        ),
    ]
