# Generated by Django 5.0.3 on 2024-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_wallet_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionbilling",
            name="amount_consumed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessionbilling",
            name="amount_refunded",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessionbilling",
            name="kwh_consumed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessionbilling",
            name="kwh_refunded",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessionbilling",
            name="time_added",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessionbilling",
            name="time_consumed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessionbilling",
            name="time_refunded",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
