# Generated by Django 5.0.3 on 2024-03-21 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCommissionMemberGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host_type', models.CharField(default='SUB-CSMS', max_length=255)),
                ('enable_user_wise_bank_settlement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('reason', models.CharField(max_length=255)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SettlementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCommissionMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission', models.FloatField(default=0)),
                ('commission_type', models.CharField(default='PERCENT', max_length=255)),
                ('max_amount', models.FloatField()),
                ('min_amount', models.FloatField()),
                ('min_threshold', models.FloatField()),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='Admin', max_length=255)),
                ('expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partner_commission_member_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_members', to='partners.partnercommissionmembergroup')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='UNPAID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='users.sessionbilling')),
                ('charger_commission_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='partners.partnercommissionmember')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('micr_code', models.CharField(max_length=9)),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('partner_commission_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='partners.partnercommissionmember')),
            ],
        ),
        migrations.CreateModel(
            name='ChargerCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission', models.FloatField(default=0)),
                ('commission_type', models.CharField(default='PERCENT', max_length=255)),
                ('max_amount', models.FloatField()),
                ('min_amount', models.FloatField()),
                ('min_threshold', models.FloatField()),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='Admin', max_length=255)),
                ('expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('charger_commission_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_charger_commissions', to='partners.partnercommissionmembergroup')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerEmployeeList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('list_type', models.CharField(default='Default Driver List', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_commission_member_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_lists', to='partners.partnercommissionmembergroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserPartnerEmployeeList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('pin', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('host_custom_user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to='partners.partneremployeelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
