# Generated by Django 5.0.3 on 2024-03-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnercommissionmembergroup",
            name="host_type",
            field=models.CharField(default="CORPORATE", max_length=255),
        ),
    ]
