# Generated by Django 5.0.3 on 2024-04-03 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0002_alter_partnercommissionmembergroup_host_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerCommissionMemberGroupPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("percent_discount_enable", models.BooleanField(default=True)),
                ("price", models.FloatField()),
                ("monthly_kwh_limit", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                ("type", models.CharField(default="CHARGING", max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="partnercommissionmember",
            name="max_amount",
        ),
        migrations.RemoveField(
            model_name="partnercommissionmember",
            name="min_amount",
        ),
        migrations.CreateModel(
            name="PlanPartnerEmployeeList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expiry", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "partner_employee_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_users",
                        to="partners.partneremployeelist",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_users",
                        to="partners.partnercommissionmembergroupplan",
                    ),
                ),
            ],
        ),
    ]
