# Generated by Django 5.0.3 on 2024-03-20 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charger_id', models.CharField(max_length=50, unique=True)),
                ('meter_value_interval', models.IntegerField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_csms', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('price_per_kwh', models.FloatField(default=20)),
                ('verified', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('AC', 'AC'), ('DC', 'DC'), ('BOTH', 'BOTH')], default='AC', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChargerConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('readonly', models.BooleanField(default=False)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='ocpp_app.charger')),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('connector_id', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Preparing', 'Preparing'), ('Charging', 'Charging'), ('SuspendedEVSE', 'SuspendedEVSE'), ('SuspendedEV', 'SuspendedEV'), ('Finishing', 'Finishing'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable'), ('Faulted', 'Faulted')], default='Unavailable', max_length=20)),
                ('type', models.CharField(choices=[('IEC60309', 'IEC60309'), ('CCS2', 'CCS2'), ('CCS1', 'CCS1'), ('CHADEMO', 'CHADEMO'), ('TYPE1', 'TYPE1'), ('TYPE2', 'TYPE2'), ('IEC62196', 'IEC62196'), ('3PIN', '3PIN')], default='CCS1', max_length=20)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='ocpp_app.charger')),
            ],
        ),
        migrations.CreateModel(
            name='IdTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idtag', models.CharField(max_length=50, unique=True)),
                ('parent_idtag', models.CharField(blank=True, max_length=50, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('meter_start', models.FloatField()),
                ('meter_stop', models.FloatField(blank=True, null=True)),
                ('reservation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('limit', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('DeAuthorized', 'DeAuthorized'), ('EmergencyStop', 'EmergencyStop'), ('EVDisconnected', 'EVDisconnected'), ('HardReset', 'HardReset'), ('Local', 'Local'), ('Other', 'Other'), ('PowerLoss', 'PowerLoss'), ('Reboot', 'Reboot'), ('Remote', 'Remote'), ('SoftReset', 'SoftReset'), ('UnlockCommand', 'UnlockCommand'), ('Server', 'Server'), ('Timeout', 'Timeout')], max_length=50)),
                ('limit_type', models.CharField(choices=[('KWH', 'KWH'), ('TIME', 'TIME'), ('SOC', 'SOC'), ('FULL', 'FULL')], default='KWH', max_length=10)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ocpp_app.connector')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_sessions', to='ocpp_app.idtag')),
                ('stop_id_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_sessions', to='ocpp_app.idtag')),
            ],
        ),
    ]
