# Generated by Django 5.0.3 on 2024-03-21 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocpp_app', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='charger_commission_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocpp_charger_commissions', to='partners.partnercommissionmembergroup'),
        ),
        migrations.AddField(
            model_name='chargerconfig',
            name='charger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='ocpp_app.charger'),
        ),
        migrations.AddField(
            model_name='connector',
            name='charger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='ocpp_app.charger'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ocpp_app.connector'),
        ),
        migrations.AddField(
            model_name='idtag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='id_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_sessions', to='ocpp_app.idtag'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='stop_id_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_sessions', to='ocpp_app.idtag'),
        ),
        migrations.AddField(
            model_name='metervalues',
            name='charger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_values', to='ocpp_app.charger'),
        ),
        migrations.AddField(
            model_name='metervalues',
            name='charging_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_values', to='ocpp_app.chargingsession'),
        ),
        migrations.AddField(
            model_name='metervalues',
            name='connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_values', to='ocpp_app.connector'),
        ),
    ]
