# Generated by Django 5.0.3 on 2024-03-21 10:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocpp_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
