# Generated by Django 5.0.3 on 2024-04-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp_app", "0003_alter_chargingsession_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingsession",
            name="stop_id_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stop_sessions",
                to="ocpp_app.idtag",
            ),
        ),
    ]
